name: setup-developer-environment
inputs:
  python-version:
    description: 'Specify the python version to use'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - run: |
        pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
