name: test-suite

on: [push]

jobs:
  linting:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        py-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-dev-environment
        with:
          python-version: ${{matrix.py-version}}

      - name: run-type-check
        run: mypy --strict hvac

      - name: run-black
        run: black --check --verbose hvac

  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        py-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-dev-environment
        with:
          python-version: ${{matrix.py-version}}

      - name: run-tests
        run: python -m pytest -v
