name: test-suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '30 22 * * 0'
  workflow_dispatch:
 
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        py-version: ["3.9", "3.10", "3.11"]
    
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-dev-env
        with:
          python-version: ${{matrix.py-version}}

      - name: run-tests
        run: |
          python -m pytest -v
