name: test-suite

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        py-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2

      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.py-version}}

      - name: install-pytest
        run: pip install pytest

      - name: run-tests
        run: python -m pytest -v
